# Generated by Django 6.0.2 on 2026-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/'),
        ),
    ]
