# Generated by Django 5.2.7 on 2026-03-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
